parameters:
    payline.class: Stloc\Bundle\PaylineBundle\PaylineService
    payline.options:
        PAYMENT_CURRENCY: 978
        ORDER_CURRENCY: 978
        SECURITY_MODE: 
        LANGUAGE_CODE: 
        PAYMENT_ACTION: 101
        PAYMENT_MODE: CPT
        CANCEL_URL: http://www.example.com/return1
        NOTIFICATION_URL: http://www.example.com/return2
        RETURN_URL: http://www.example.com/return3
        CUSTOM_PAYMENT_TEMPLATE_URL: 
        CUSTOM_PAYMENT_PAGE_CODE: 
        CONTRACT_NUMBER: '0011223'
        CONTRACT_NUMBER_LIST: 
        SECOND_CONTRACT_NUMBER_LIST: 
    payline.identification:
        MERCHANT_ID: '11223344556677'
        ACCESS_KEY: YourAccesKey
        PROXY_HOST: 
        PROXY_PORT: 
        PROXY_LOGIN: 
        PROXY_PASSWORD: 
        PRODUCTION: false

services:
    payline:
        class: %payline.class%
        arguments: [%payline.options%, %payline.identification%]
#        arguments: [@service_id, "plain_value", %parameter%]